webtalk_init -webtalk_dir C:/Users/Zain/Documents/GitHub/Vivado-9-Bit-Processor/CA/CA.sim/sim_1/behav/xsim/xsim.dir/pcTestBench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar 10 16:14:53 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8d03cec7-df0e-449a-b2e1-0cab8f4320d5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d95f1713f30042e2b1971e0cb641906a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "8.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2663003401 -regid "" -xml C:/Users/Zain/Documents/GitHub/Vivado-9-Bit-Processor/CA/CA.sim/sim_1/behav/xsim/xsim.dir/pcTestBench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Zain/Documents/GitHub/Vivado-9-Bit-Processor/CA/CA.sim/sim_1/behav/xsim/xsim.dir/pcTestBench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Zain/Documents/GitHub/Vivado-9-Bit-Processor/CA/CA.sim/sim_1/behav/xsim/xsim.dir/pcTestBench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
